language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then mv phpspec.no-coverage.yml phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then mv phpspec.no-coverage.yml phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpspec.no-coverage.yml phpspec.yml; fi

install:
  - travis_retry composer install

script:
  - composer test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
